version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000" # Map backend container port to localhost
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - MONGO_URI=mongodb://mongo:27017/employeedb

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000" # Map frontend container port to localhost
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
